---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: echo-client
spec:
  selector:
    matchLabels:
      app: echo-client
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-client
    spec:
      containers:
      - image: purecap/python38_socket_echo_client:1.0
        imagePullPolicy: Always
        name: app-echo-client
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10; done"]
        ports:
        - containerPort: 9999

