---
apiVersion: v1
kind: Service
metadata:
  name: ext-socket
spec:
  ports:
  - port: 9999
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ext-socket
subsets:
  - addresses:
    - ip: 100.64.17.136 # 100.64.17.136  54.219.215.60
    ports:
    - port: 9999


