---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: multisocket-client
spec:
  selector:
    matchLabels:
      app: multisocket-client
  replicas: 1
  template:
    metadata:
      labels:
        app: multisocket-client
    spec:
      containers:
      - image: purecap/python38_socket_client:1.0
        imagePullPolicy: Always
        name: app-multisocket-client
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10; done"]
        ports:
        - containerPort: 9999

