---
apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  ports:
  - port: 9999
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service
subsets:
  - addresses:
    - ip: 100.64.17.136
    ports:
    - port: 9999
